### ISSUE TITLE
short question

### ISSUE THREAD

**Issue by TMHBOFH** [mprasil/docker-bitwarden#1]
Hi,
at first big thanks for your work.
At the first look all running fine with your docker image.
My question is only what must i do to enable 2-Factor Authentication.

Thanks for help

best regards

**Comment by mprasil** [comment]
Hi, this [commit here](https://github.com/jcs/bitwarden-ruby/commit/703d5703cf02a74f3feb46dd775a4c96001debcc) suggest that there are some pieces of code in place for 2FA, however I'm not entirely sure if it's fully usable.

Going to Vault (the web interface) the recovery code retrieval fails because the API endpoint for that isn't implemented. (`/api/two-factor/get-recover`) Same for the endpoints that would implement the individual 2FA methods.

In theory you should be able to `docker exec` into the container and run the following to run the `activate_totp.rb` script:

```bash
export BUNDLE_PATH=/bitwarden/api/vendor/bundle/ruby/2.4.0/
cd /bitwarden/api
bundle exec ruby tools/activate_totp.rb -u your_user@example.com
```
But I haven't tried that. 

I suggest asking directly [bitwarden-ruby](https://github.com/jcs/bitwarden-ruby) guys.

**Comment by TMHBOFH** [comment]
thanks for the fast reply
I will looking into your tips.
