### ISSUE TITLE
Better ENV handling for ALLOW_SIGNUPS

### ISSUE THREAD

**Issue by TMHBOFH** [mprasil/docker-bitwarden#2]
Hi,

universal has update his repo. It would be nice if you can build a new docker-image.
Please also edit the file

service/api/run
----------------------------------------------------------------------------
#!/bin/sh

export RACK_ENV="${RACK_ENV:-"production"}"
export BUNDLE_PATH=/bitwarden/api/vendor/bundle/ruby/2.4.0/

cd /bitwarden/api

bundle exec rackup -p 4567 config.ru
----------------------------------------------------------------------------
In my tests the registraion of new user works also if i set ALLOW_SIGNUPS to 0. Only if the env ALLOW_SIGNUPS is not set , is the registion also  disabeld

Big Thanks and best regards

**Comment by mprasil** [comment]
Hi, I've rebuilt the image couple times already. I believe the latest additions branch is already in docker hub.

You're right about the signups variable - just reading the ruby code now, it looks like it just tests for presence of the variable rather than the value. I'm going to add some extra logic there to handle that.

**Comment by mprasil** [comment]
Okay, so I've did a quick fix for that in f0e31fb7f6112f0469e2d11fae59ba8dfe656437 so you should be able to disable signups by setting `SIGNUPS` variable to something else than "yes".

This way it still defaults to enabled signups (actually I've set the default properly in c44cf042142086dbd86b70c2e6546938eee0539f) while giving you a way to disable it rather than the other way around.

Give it a try.
